services:
  keystonetech-db:
    image: postgres:17
    container_name: "keystonetech-db"
    hostname: keystonetech-db
    restart: unless-stopped

    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - TZ=UTC
    
    volumes:
      - keystonetech-db-data:/var/lib/postgresql/data

    networks:
      - remnawave-network

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 3s
      timeout: 10s
      retries: 3
    

  keystonetech-redis:
    image: valkey/valkey:9-alpine
    container_name: "keystonetech-redis"
    hostname: keystonetech-redis
    restart: unless-stopped

    command: [ "--requirepass", "${REDIS_PASSWORD}" ]

    volumes:
      - keystonetech-redis-data:/data

    networks:
      - remnawave-network

    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 3s
      timeout: 10s
      retries: 3
    

  keystonetech:
    &keystonetech
    image: ghcr.io/keystonetech/keystonetech:latest
    container_name: "keystonetech"
    hostname: keystonetech
    restart: unless-stopped

    env_file:
      - .env
    environment:
      RESET_ASSETS: "${RESET_ASSETS:-false}"

    depends_on:
        keystonetech-db:
          condition: service_healthy
        keystonetech-redis:
          condition: service_healthy

    volumes:
      - ./logs:/opt/keystonetech/logs
      - ./assets:/opt/keystonetech/assets

    networks:
      - remnawave-network
    

  keystonetech-taskiq-worker:
    <<: *keystonetech
    container_name: "keystonetech-taskiq-worker"
    hostname: keystonetech-taskiq-worker
    command: taskiq worker src.infrastructure.taskiq.worker:worker 
      --tasks-pattern src/infrastructure/taskiq/tasks -fsd

    depends_on:
        keystonetech-redis:
          condition: service_healthy
        keystonetech-db:
          condition: service_healthy


  keystonetech-taskiq-scheduler:
    <<: *keystonetech
    container_name: "keystonetech-taskiq-scheduler"
    hostname: keystonetech-taskiq-scheduler
    command: taskiq scheduler src.infrastructure.taskiq.scheduler:scheduler
      --tasks-pattern src/infrastructure/taskiq/tasks -fsd

    depends_on:
        keystonetech-redis:
          condition: service_healthy
        keystonetech-db:
          condition: service_healthy


networks:
  remnawave-network:
    name: remnawave-network 
    driver: bridge 
    external: true

volumes:
  keystonetech-db-data:
    name: keystonetech-db-data
    driver: local
    external: false
    
  keystonetech-redis-data:
    name: keystonetech-redis-data
    driver: local
    external: false